from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
import io
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
from ..models import Deck, Flashcard, User
from app.core.security import get_current_user
from ..database import get_db

router = APIRouter(prefix="/deck", tags=["Export Deck"])

@router.get("/{deck_id}/export")
async def export_deck(
    deck_id: str,
    format: str = "pdf",
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    if not current_user.is_premium:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This feature is only available for premium users"
        )
    
    # Fetch deck
    deck_result = await db.execute(select(Deck).where(Deck.id == deck_id))
    deck = deck_result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found")

    # Fetch flashcards
    flashcards_result = await db.execute(select(Flashcard).where(Flashcard.deck_id == deck_id))
    flashcards = flashcards_result.scalars().all()

    # PDF Export Logic
    if format == "pdf":
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=40, leftMargin=40,
            topMargin=60, bottomMargin=40,
            title=f"{deck.name} - Flashcards"
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            fontSize=22,
            textColor=colors.HexColor("#1f77b4"),
            spaceAfter=20
        )
        normal_style = ParagraphStyle(
            "NormalStyle",
            parent=styles["Normal"],
            fontSize=12,
            spaceAfter=10,
        )

        # Start document content
        story = []

        # === APP LOGO ===
        try:
            # You can use your own hosted logo or static path
            
            story.append(Image(logo_path, width=100, height=50))
        except Exception:
            pass

        # === Title and Meta ===
        story.append(Paragraph(f"{deck.name}", title_style))
        if deck.description:
            story.append(Paragraph(deck.description, normal_style))

        story.append(Paragraph(
            f"Exported by: <b>{current_user.name}</b> ({current_user.email})<br/>"
            f"Export Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            ParagraphStyle("MetaStyle", fontSize=10, textColor=colors.gray, spaceAfter=20)
        ))

        # === Table Header ===
        table_data = [["#", "Question", "Answer"]]
        for i, f in enumerate(flashcards, start=1):
            table_data.append([str(i), f.question, f.answer])

        # === Table Styling ===
        table = Table(table_data, colWidths=[30, 220, 220])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1f77b4")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.gray),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.gray),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey]),
        ]))
        story.append(table)

        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by FlashAI Assistant", ParagraphStyle(
            "FooterStyle", fontSize=9, textColor=colors.HexColor("#777777"), alignment=1
        )))

        doc.build(story)
        buffer.seek(0)

        headers = {"Content-Disposition": f"attachment; filename={deck.name}_deck.pdf"}
        return StreamingResponse(buffer, media_type="application/pdf", headers=headers)

    raise HTTPException(status_code=400, detail="Only PDF format customization supported for now")
