from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
import io
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime
from ..models import Deck, Flashcard, User
from app.core.security import get_current_user
from ..database import get_db

from uuid import UUID

router = APIRouter(prefix="/decks", tags=["Export Deck"])

@router.get("/{deck_id}/export")
async def export_deck(
    deck_id: UUID,
    format: str = "pdf",
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    
    deck_result = await db.execute(select(Deck).where(Deck.id == deck_id, Deck.user_id == current_user.id))
    deck = deck_result.scalar_one_or_none()
    if not deck:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Deck not found or access denied")

    flashcards_result = await db.execute(select(Flashcard).where(Flashcard.deck_id == deck_id))
    flashcards = flashcards_result.scalars().all()

    if format == "pdf":
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=50, leftMargin=50,
            topMargin=50, bottomMargin=50,
            title=f"{deck.name} - Flashcards"
        )

        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            "TitleStyle",
            parent=styles["Title"],
            fontSize=24,
            textColor=colors.HexColor("#2563eb"),
            spaceAfter=15,
            alignment=1
        )
        
        meta_style = ParagraphStyle(
            "MetaStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.gray,
            spaceAfter=20,
            alignment=1
        )

        label_style = ParagraphStyle(
            "LabelStyle",
            parent=styles["Normal"],
            fontSize=12,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#1e40af"),
            spaceBefore=15,
            spaceAfter=5,
        )

        content_style = ParagraphStyle(
            "ContentStyle",
            parent=styles["Normal"],
            fontSize=11,
            leading=14,
            leftIndent=15,
            spaceAfter=10,
        )

        footer_style = ParagraphStyle(
            "FooterStyle",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.gray,
            alignment=1,
            spaceBefore=30
        )

        story = []

        story.append(Paragraph(f"{deck.name}", title_style))
        if deck.description:
            desc_style = ParagraphStyle("Desc", parent=styles["Normal"], alignment=1, spaceAfter=10, italic=True)
            story.append(Paragraph(deck.description, desc_style))

        story.append(Paragraph(
            f"Exported by: <b>{current_user.name}</b> | Date: {datetime.now().strftime('%B %d, %Y')}",
            meta_style
        ))
        
        story.append(Spacer(1, 10))

        for i, f in enumerate(flashcards, start=1):
            story.append(Paragraph(f"Flashcard {i}", ParagraphStyle("Idx", parent=label_style, fontSize=14, textColor=colors.black, spaceBefore=20)))
            
            story.append(Paragraph("Question:", label_style))
            story.append(Paragraph(f.question, content_style))
            
            if f.options:
                for opt_key, opt_val in f.options.items():
                    opt_text = f"<b>{opt_key}:</b> {opt_val}"
                    story.append(Paragraph(opt_text, ParagraphStyle("Opt", parent=content_style, leftIndent=30, spaceAfter=2)))
            
            story.append(Paragraph("Answer:", label_style))
            
            final_answer = f.answer or ""
            if f.options and f.answer in f.options:
                final_answer = f"({f.answer}) {f.options[f.answer]}"
            
            story.append(Paragraph(final_answer, ParagraphStyle("Ans", parent=content_style, textColor=colors.HexColor("#16a34a"))))
            
            from reportlab.platypus import HRFlowable
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceBefore=10, spaceAfter=5))

        story.append(Paragraph("Generated by FlashAI Assistant - Enhance Your Learning", footer_style))

        doc.build(story)
        buffer.seek(0)

        filename = f"{deck.name.replace(' ', '_')}_Flashcards.pdf"
        headers = {"Content-Disposition": f"attachment; filename={filename}"}
        return StreamingResponse(buffer, media_type="application/pdf", headers=headers)

    raise HTTPException(status_code=400, detail="Only PDF format customization supported for now")
